[package]
name = "assets"
version = "0.1.0"
edition = "2024"

[dependencies]
telemetry.workspace = true

# External dependencies
tracing.workspace = true
once_cell = "1.21.3"
rust-embed = { version = "8.9.0", features = ["include-exclude"] }
