[workspace]
resolver = "3"
members = ["html/*", "engine", "network", "assets", "utilities/*", "storage", "cookies"]

[workspace.dependencies]
tracing = "0.1"
tokio = { version = "1.44", features = ["full"] }
cookie = "0.18.1"
criterion = "0.7"
