[workspace]
resolver = "3"
members = [
    "assets",
    "browser-core",
    "cookies",
    "css/css-cssom",
    "css/css-parser",
    "css/css-selectors",
    "css/css-style",
    "css/css-tokenizer",
    "engine",
    "errors",
    "html/html-dom",
    "html/html-parser",
    "html/html-syntax",
    "html/html-tokenizer",
    "layout",
    "network",
    "renderer",
    "storage",
    "ui",
    "utilities/constants",
    "utilities/telemetry",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
assets = { path = "assets" }
cookies = { path = "cookies" }
css-cssom = { path = "css/css-cssom" }
css-parser = { path = "css/css-parser" }
css-tokenizer = { path = "css/css-tokenizer" }
css-selectors = { path = "css/css-selectors" }
css-style = { path = "css/css-style" }
browser-core = { path = "browser-core" }
errors = { path = "errors" }
html-dom = { path = "html/html-dom" }
html-parser = { path = "html/html-parser" }
html-syntax = { path = "html/html-syntax" }
html-tokenizer = { path = "html/html-tokenizer" }
layout = { path = "layout" }
network = { path = "network" }
renderer = { path = "renderer" }
storage = { path = "storage" }
ui = { path = "ui" }
constants = { path = "utilities/constants" }
telemetry = { path = "utilities/telemetry" }


# External dependencies
async-trait = "0.1.89"
tracing = "0.1.43"
tokio = { version = "1.44", features = ["full"] }
cookie = "0.18.1"
criterion = "0.8.1"
http = "1.3.1"
url = "2.5.4"

[profile.release]
debug = true
