[workspace]
resolver = "3"
members = [
    "assets",
    "browser-core",
    "cookies",
    "engine",
    "errors",
    "html/html-dom",
    "html/html-parser",
    "html/html-syntax",
    "html/html-tokenizer",
    "network",
    "storage",
    "utilities/*"
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
# Local dependencies
assets = { path = "assets" }
browser-core = { path = "browser-core" }
cookies = { path = "cookies" }
errors = { path = "errors" }
html-dom = { path = "html/html-dom" }
html-parser = { path = "html/html-parser" }
html-syntax = { path = "html/html-syntax" }
html-tokenizer = { path = "html/html-tokenizer" }
network = { path = "network" }
storage = { path = "storage" }
constants = { path = "utilities/constants" }
parsing = { path = "utilities/parsing" }
telemetry = { path = "utilities/telemetry" }


# External dependencies
tracing = "0.1.43"
tokio = { version = "1.44", features = ["full"] }
cookie = "0.18.1"
criterion = "0.8.1"
http = "1.3.1"
url = "2.5.4"
