[workspace]
resolver = "3"
members = ["html/*", "engine", "network", "assets", "utilities/*"]

[workspace.dependencies]
tracing = "0.1"
tokio = { version = "1.44", features = ["full"] }
criterion = "0.7"
