[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = "0.3"
cookies = { path = "../cookies" }
constants = { path = "../utilities/constants" }
ui = { path = "../ui" }
http = { workspace = true }
