[package]
name = "cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
browser-core.workspace = true
constants.workspace = true

tracing.workspace = true
tokio.workspace = true
clap = { version = "4.5.54", features = ["derive"] }
