[package]
name = "cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
constants.workspace = true

# External dependencies
tracing.workspace = true
tokio.workspace = true
clap = { version = "4.5.54", features = ["derive"] }
