[package]
name = "cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
constants.workspace = true
preferences.workspace = true

# External dependencies
clap.workspace = true
tracing.workspace = true
tokio.workspace = true
