[package]
name = "browser-config"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
constants.workspace = true
storage.workspace = true

# External dependencies
serde.workspace = true
toml = "0.9.11"
