[package]
name = "assets"
version = "0.1.0"
edition = "2024"

[dependencies]
telemetry = { path = "../utilities/telemetry" }
tracing = { workspace = true }
once_cell = "1.21.3"
rust-embed = { version = "8.7.2", features = ["include-exclude"] }
