[package]
name = "css-cssom"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
css-parser.workspace = true

# External dependencies
serde.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "cssom_benchmark"
harness = false
