[package]
name = "preferences"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
constants.workspace = true
storage.workspace = true

# External dependencies
clap.workspace = true
serde.workspace = true
toml = "0.9.11"
