[package]
name = "io"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
constants.workspace = true
storage.workspace = true
network = { workspace = true, optional = true }
cookies  = { workspace = true, optional = true }

# External dependencies
dirs = "6.0.0"
tracing.workspace = true
thiserror.workspace = true
url = { workspace = true, optional = true}
tokio = { workspace = true, optional = true }
rust-embed = { version = "8.9.0", features = ["include-exclude"] }

[features]
default = []
network = ["dep:url", "dep:tokio", "dep:network", "dep:cookies"]
