[package]
name = "io"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
constants.workspace = true
database.workspace = true
storage.workspace = true
network = { workspace = true, optional = true }
cookies  = { workspace = true, optional = true }

# External dependencies
dirs = "6.0.0"
httpdate.workspace = true
postcard.workspace = true
rust-embed = { version = "8.9.0", features = ["include-exclude"] }
rusqlite.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio = { workspace = true, optional = true }
tracing.workspace = true
url = { workspace = true, optional = true}

[features]
default = []
network = ["dep:url", "dep:tokio", "dep:network", "dep:cookies"]


[dev-dependencies]
serial_test.workspace = true
