[package]
name = "io"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
constants.workspace = true
network.workspace = true
cookies.workspace = true

# External dependencies
async-trait.workspace = true
url.workspace = true
tracing.workspace = true
thiserror.workspace = true
tokio.workspace = true
rust-embed = { version = "8.9.0", features = ["include-exclude"] }
