[package]
name = "io"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
constants.workspace = true

# External dependencies
tracing.workspace = true
once_cell = "1.21.3"
rust-embed = { version = "8.9.0", features = ["include-exclude"] }
